### PR TITLE
Make `dev server respond with index.html to all unrecognized requests

### PR DESCRIPTION
**Pull request by cibernox**
As of today, if anyone uses this template to create an app with some kind of routing library (e.g. `svelte-routing`) and they reload in any url but the root, the server won't respond.

I think this is not a good default for this template. Passing `--single index.html` will serve the index.html instead, which I think is nicer default.

### CODE REVIEW

**Comment by Conduitry** [comment]
This was the behavior for a while, but it was consciously removed in #88/#90.

**Comment by lukeed** [comment]
Hey there,

We _just_ moved away from this default behavior in #90. And with that came [README instructions](https://github.com/sveltejs/template#single-page-app-mode) to re-enable SPA mode (as you've done).

Basically, if you go through our PR/issue history, you'll see that the population is pretty evenly split towards wanting/not wanting SPAs as the default behavior

**Comment by lukeed** [comment]
Oh hah, you beat me

**Comment by Conduitry** [comment]
Another factor was the [sheer](https://github.com/sveltejs/template/issues/56) [number](https://github.com/sveltejs/template/issues/92) [of](https://github.com/sveltejs/svelte/issues/3378) [issues](https://github.com/sveltejs/svelte/issues/3523) [like](https://github.com/sveltejs/svelte/issues/3600) [this](https://github.com/sveltejs/svelte/issues/3688).

**Pull request closed without merging**
