### PR TITLE
add svelte testing library

### PR DESCRIPTION
**Pull request by webmasterdevlin**
This pull request has added npm packages, which help developers test their components using the Svelte Testing Library. It also has an App spec file to show a quick sample of how to write tests.

### CODE REVIEW

**Comment by Conduitry** [comment]
Thanks for the PR, but I'm not sure we're ready to endorse a particular testing library yet.

I'm not sure what the `.babelrc` here is for, but we've also been discouraging people from configuring Babel that way, because I don't think there's a way to make it apply to the contents of `node_modules`, and compiled components have imports from `.../node_modules/svelte/internal` that also need to be transpiled to work on older browsers.

**Comment by webmasterdevlin** [comment]
@Conduitry totally okay. The Babelrc is for the es6 import module to work but I know that there's a better way of doing. =D

Thanks for the comment by the way. =)

**Comment by antony** [comment]
Thanks for the PR! Apologies that it didn't get in. I'm closing it until there is greater clarity on testing libraries.

**Comment by TheManSpeaker** [comment]
I was thinking of contributing this myself, until I searched the PRs and found this one was already attempted - has anything changed as far as endorsing a particular testing library in the time since this PR was closed? Is there potential to at least include some kind of instructions and/or basic setup for testing of some sort?

This PR is pretty much exactly how I set up testing for my svelte projects, so it would be cool if this were included in the template by default - or even better, if there were a nicer way to do this (i.e. not needing a babel config just for esm imports to work in your tests)

**Pull request closed without merging**
