### PR TITLE
setup script for IE11

### PR DESCRIPTION
**Pull request by j3n57h0m45**
This enables to setup the template for building in IE11 compatible mode.

### CODE REVIEW

**Comment by antony** [comment]
Thanks for this, and we appreciate the hard work. However, IE11 is in the process of being forcefully removed from existence by it's authors, so we are not intending to provide any sort of out-of-the box support our endorsement of it.

**Comment by j3n57h0m45** [comment]
Well especially in corporate environment IE11 and HTA are still a thing. I thought it would be helpfull to get a head start, if others are (as well) confronted with that "target" for their projects.

**Comment by antony** [comment]
I appreciate that but it's not something we want to encourage.

If anything the dev community as a whole needs to discourage it.

If people need to support IE11 (I myself do - see https://github.com/antony/sapper-ie) then they are free to do so and Svelte won't prevent it. But Svelte is about modern JS and standards based browsers.

**Comment by j3n57h0m45** [comment]
> If people need to support IE11 (I myself do - see https://github.com/antony/sapper-ie) then they are free to do so and Svelte won't prevent it. But Svelte is about modern JS and standards based browsers.

Looks like there is still a need for a legacy template(s) :) 

Nevermind I think we can close this PR. I appreciate your candor.

**Pull request closed without merging**
