### PR TITLE
Change absolute path to relative path in index.html

### PR DESCRIPTION
**Pull request by JumpLao**

### CODE REVIEW

**Comment by Conduitry** [comment]
@lukeed You just changed these to absolute in #46 - do you care to weigh in?

**Comment by frederikhors** [comment]
Can I ask why, @JumpLao?

**Comment by Conduitry** [comment]
I evidently shouldn't comment on issues really early in the morning, because the reason for these being absolute is pretty obvious: With #46, this template was changed to be more suited for people who want to run SPAs from it. All URLs are served from the root index.html, so we need absolute paths to these files, so that they can be resolved from any nested path.

Having this set up as a SPA template makes the most sense to me as a default, so I'm closing this. If someone has other needs, they can edit their own copy of the template before starting their project.

**Comment by lukeed** [comment]
Right, most people are running SPAs with nested pathing. In the rarer cases where this isn't true, I think it's okay to manually convert to relative paths

**Pull request closed without merging**
