### PR TITLE
svelte app on div instead of body

### PR DESCRIPTION
**Pull request by doojinkang**
Svelte app is drawn on body, that is app is binding to body.
Sometimes it make difficult to embed svelte app into other html.

This commit:
Svelte app is drawn on div with id "root" for flexibility.

### CODE REVIEW

**Comment by Conduitry** [comment]
I don't think this makes sense as a default, and it makes certain styling harder. If someone wants this for their app, it's simple for them to change.

**Comment by frederikhors** [comment]
> Sometimes it make difficult to embed svelte app into other html.

Can you please explain this better?

**Comment by antony** [comment]
The purpose of a template is to be a quick get-started for anybody. You can modify your fork or cloned project of the template in any way you see fit.

**Comment by doojinkang** [comment]
> > Sometimes it make difficult to embed svelte app into other html.
> 
> Can you please explain this better?

I am converting react app to svelte, and writing blogs.
I'd like to embed app in my blog.
In this case target to <div> is better.

https://flyingmonocopter.github.io/posts/sveltepidcontrol/
Though it is korean, but you can run the app. ^^

Thank you for asking me.

**Pull request closed without merging**
