### PR TITLE
chore: bump sirv-cli

### PR DESCRIPTION
**Pull request by lukeed**
Maybe a WIP PR – I think with the changes in 1.0, it might be time to enable `--single` by default again since missing assets will 404 correctly now (#116)

Might also want to include a HTTPS or HTTP/2 step-by-step here (#128)?

### CODE REVIEW

**Comment by Conduitry** [comment]
> Any asset requests (URLs that end with an extension) ignore `--single` behavior and will send a `404` response instead of the "index.html" fallback.

Hm. That's an interesting new default behavior for SPA mode. That'll probably work most of the time, but I'm still worried that using that as the default will lead to even more confusion than there is now when it doesn't do quite the right thing. We have plenty of evidence that people won't read sirv's docs before asking questions about how to do things with this template. I don't know what the right answer is here.

**Comment by lukeed** [comment]
Yeah, we dont have to do anything, but the current `--single` behavior is the _correct_ default behavior it should have always had. It's not a surprise at all that the previous `--single` attempt(s) always caused a boat load of confusion.

**Comment by Conduitry** [comment]
The new `--single` behavior will give people problems if they try to have an SPA where some of the routes have a period in them though, right? I don't know how common that would be. Is there some precedent in other tools about how to handle this and try to make only the intended 404s be 404s?

**Comment by lukeed** [comment]
Yeah, they look for "." in the address bar. The only other way to approach it is to send a (long) default list of file extensions, which will undoubtedly need modifying anyway.

You can disable all the default "ignore" behavior by `--no-ignores` or add new patterns to ignore by passing it in: `--ignore foobar`

**Comment by lukeed** [comment]
Can we revisit this? Some people are running into issues getting old sirv & expecting new behavior: https://github.com/lukeed/sirv/issues/67#issuecomment-647027499

**Comment by lukeed** [comment]
Merging this as I still get pings about sirv issues/questions – usually along the lines of "sirv documentation doesn't match it's behavior [...] oh! the template didn't give me the latest"

We can adjust flags/documentation later as needed

**Pull request merged**
